### ISSUE TITLE
Invalid gradient

### ISSUE THREAD

**Issue by KindofCrazy** [Isaaclabe/DGD-Dynamic-3D-Gaussians-Distillation#5]
Thanks for your excellent work!
When I ran the command below, it appears the dimension went into conflict

```
python train.py -s ./data/split-cookie -m output/split-cookie --Lseg_model_path ./lseg_minimal_e200.ckpt --fundation_model "Lseg_CLIP" --semantic_dimension 512 --loss_reduce 10
```

```
Optimizing output/split-cookie
Output folder: output/split-cookie [29/11 22:04:56]
Tensorboard not available: not logging progress [29/11 22:04:56]
Found dataset.json file, assuming Nerfies data set! [29/11 22:04:58]
Reading Nerfies Info [29/11 22:04:58]
 [29/11 22:05:08]
Generating point cloud from nerfies... [29/11 22:05:08]
Loading Training Cameras [29/11 22:05:08]
Loading Test Cameras [29/11 22:05:11]
Number of points at initialisation :  20075 [29/11 22:05:11]
Training progress:   0%|                                                                                                                                                                                                  | 0/40000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 316, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations)
  File "train.py", line 231, in training
    loss.backward()
  File "/data/YangKe/app/anaconda3/envs/dgd/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/YangKe/app/anaconda3/envs/dgd/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 4 - got [20075, 1, 384] but expected shape compatible with [20075, 1, 512]
Training progress:   0%|                                                                                                                                                                                                  | 0/40000 [00:00<?, ?it/s]
```

How should I solve it? Thanks!

**Comment by Isaaclabe** [comment]
Hi, thank for you interest. 

When you want to use different foundation model, you need to setup the rasteriser with the current feature dimension you use. Here you have to change the file DGD-Dynamic-3D-Gaussians-Distillation/submodules/diff-gaussian-rasterization/cuda_rasterizer/config.h and change: 

NUM_SEMANTIC_CHANNELS 384 to NUM_SEMANTIC_CHANNELS 512

And then you can setup and run your command.

PS: for more details see the colab notebook for run on scene. 

Best, 
Isaac Labe.
